project: default
source:
  repoURL: https://airflow.apache.org
  targetRevision: '1.14'
  helm:
    values: |
      webserver:
        resources:
          requests:
            cpu: 300m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
      dag:
        persistenceEnabled: true
        gitSync:
          enabled: true
          repo: https://github.com/jrodriguezru/aflwdag
          branch: main
          subPath: dags/
  chart: airflow
destination:
  server: https://kubernetes.default.svc
  namespace: airflow
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true

