webserver:
  resources:
    requests:
      cpu: 300m
      memory: 1Gi
    limits:
      cpu: 1
      memory: 2Gi

dag:
  persistenceEnabled: true
  gitSync:
    enabled: true
    repo: https://github.com/jrodriguezru/aflwdag
    branch: main
    subPath: dags/
  
